### PR TITLE
Some Fixes

### PR DESCRIPTION
**Pull request by BlackBeltPanda**
- ~~Disable the register button in the navbar when registration is disabled~~
- Remove links to non-existent profiles in the server-status widget
- Fix inability to scroll back to the very top of a page (there's a better fix for sticky navbars, but I can't remember it right now)
- Fix embed not working
- Fix "Click to Copy" IP in server status including colon or port when port is not set or default (25565)

### CODE REVIEW

**Comment by Sylensky** [comment]
Thank you for your contribution.
Can you provide some screenshots/gifs just for references?

**Comment by Sylensky** [comment]
Might helps to fix #12.
Improves #14.

**Comment by BlackBeltPanda** [comment]
Oh, hang on, I forgot I made some changes to NamelessMC for the registration check.

**Comment by PadowYT2** [comment]
> Oh, hang on, I forgot I made some changes to NamelessMC for the registration check.

What do you mean by that? You mean you want it to be in DefaultRevamp before Nexus?

**Comment by BlackBeltPanda** [comment]
> 

No, I had assigned the $REGISTRATION_ENABLED variable in NamelessMC's navbar.php.

**Comment by BlackBeltPanda** [comment]
If anyone knows a better way to check if registration is disabled, would much appreciate it. I'm not super well-versed in Smarty lol

**Comment by PadowYT2** [comment]
```
{if $REGISTRATION_ENABLED == 1}
# code
{/if}

**Comment by BlackBeltPanda** [comment]
> ```shell
> {if $REGISTRATION_ENABLED == 1}
> # code
> {/if}
> ```

That only works if the variable's assigned to the template, though

**Comment by PadowYT2** [comment]
Oh, yea, your right

**Comment by PadowYT2** [comment]
Seems good, but I've pushed an another update, I can update it

**Comment by PadowYT2** [comment]
nvm, it is alright

**Pull request merged**
