### PR TITLE
Gallery rework

### PR DESCRIPTION
**Pull request by Sylensky**

### CODE REVIEW

**Comment by Sylensky** [comment]
the missing features from #8 are still not implemented.
dark mode is hardcoded for now and might get fixed when #32 is getting reworked.

**Comment by PadowYT2** [comment]
Seems good, except, can you change the color of the popup video to `#303030`?
image

**Comment by Sylensky** [comment]
I will have a look this evening

**Comment by Sylensky** [comment]
Were you able to check yet?

**Comment by PadowYT2** [comment]
Whoops, I'm sorry for forgetting to merge, it works and looks great

**Pull request merged**
