### PR TITLE
Ghost Module support

### PR DESCRIPTION
**Pull request by Sylensky**
This PR adds support for the Ghost Module made by ColdFire. Kodus for providing me the necessery sources :)

There is one little thing that bothers me but wasn't able to resolve yet:

- [ ] I am unable to format the pagination properly (probably because iam dumb) Any input is appreciated else there won't be any pagination for now.

### CODE REVIEW

**Comment by Sylensky** [comment]
Here is the example view on how the home looks like.
image

**Comment by Sylensky** [comment]
and after clicking on one post:
image

**Comment by Sylensky** [comment]
found a solution to stack posts on mobile thanks to Kaspian.

**Review by PadowYT2 — COMMENTED** [review]
So what's up with the white theme?

**Comment by Sylensky** [comment]
the white theme is lacking the proper background color for the posts which i don't know how to pass to the css. Any idea?

**Comment by PadowYT2** [comment]
You can make the bg in .tpl with style="background-color: #212121" and make the style in {if $DARK_MODE eq 1} (or something like that)

**Comment by PadowYT2** [comment]
Well, when #32 is done, it will have a color for white mode, for right now I'll merge

**Pull request merged**
