### PR TITLE
Some grammar fixes

### PR DESCRIPTION
**Pull request by itzJOHv**

### CODE REVIEW

**Comment by itzJOHv** [comment]
yay

**Comment by itzJOHv** [comment]
sorry for spamming commits btw

**Comment by Sylensky** [comment]
Thanks for the contribution.
Allthough i like your commit seperation but i would have added a different commit message.

Maybe something like this would fit better:
`translation: widget.php`
This way it will be easier to track the commit history.

**Comment by itzJOHv** [comment]
> Thanks for the contribution.
> Allthough i like your commit seperation but i would have added a different commit message.
> 
> Maybe something like this would fit better:
> `translation: widget.php`
> This way it will be easier to track the commit history. 

Thanks, I'll note that for future reference.

**Comment by PadowYT2** [comment]
And if you made words uncapitalized, maybe do the same in EnglishUK?

**Comment by itzJOHv** [comment]
> And if you made words uncapitalized, maybe do the same in EnglishUK?

kk, imma do that once I'll be at least half done with my bots update.

**Comment by Sylensky** [comment]
Any updates on this one? @itzJOHv

**Comment by itzJOHv** [comment]
> Any updates on this one? @itzJOHv 

I'm currently not home, so I don't have access to my pc. I'll be home in the next 4-5 days tho.

**Comment by PadowYT2** [comment]
@itzJOHv

**Comment by itzJOHv** [comment]
@PadowYT2

**Review by PadowYT2 — APPROVED** [review]
Now it is all good

**Pull request merged**
