### PR TITLE
Fixes & additions

### PR DESCRIPTION
**Pull request by Sylensky**
I fixed some minor styling issues that were bothering me.

Additionally iam not sure why the index page at commit b14e51a108365b45430924e1d6233df404a4e19d didnt have a spacer so please check if that is a concern on your side.
If you want to check how it looks hit me up and i share you the link where i have theses changes applied.

### CODE REVIEW

**Review by PadowYT2 — COMMENTED** [review]
Any screenshots?

**Comment by Sylensky** [comment]
Wiki: repositioning and divider addition
image
Status: static icons instead of querying the favicon
image
Staff: same color for group name and username
image
Resources: cleaner look and hoverable table item is clickable with the link
image
image
image
Tebex: card background color is template color setting, latest purchase amount with template color
image
Rules: inverted the segment
image
Home: there was no space between the background image and the first post. please check on your side if that happened
image

**Review by PadowYT2 — APPROVED** [review]
Looks all good!
The space exists and it changed (just refreshed the page I noticed it)

**Comment by PadowYT2** [comment]
I've noticed an another problem
https://cdn.padow.ru/wLSo
Also, maybe making a space?
https://cdn.padow.ru/hXO0

**Comment by Sylensky** [comment]
Ignore the socialize part. Theres soon a rework incoming.
You mean a space between the green wiki header and the item below?

**Comment by PadowYT2** [comment]
> Ignore the socialize part. Theres soon a rework incoming. You mean a space between the green wiki header and the item below?

Yep, because it literally has no space

**Comment by Sylensky** [comment]
d4e2bc1
image

**Pull request merged**
