### PR TITLE
Navbar updates & images removed

### PR DESCRIPTION
**Pull request by PadowYT2**
This fixes phones look and a note that `Sticky Navbar?` is buggy and other. Not sure how removing Fomantic's CDNs and jQuery helped, but it did

### CODE REVIEW

**Review by Sylensky — CHANGES_REQUESTED** [review]
Can you do the same in russian language?

**Comment by Sylensky** [comment]
Can you show some images before and after your additions?

**Comment by PadowYT2** [comment]
> Can you do the same in russian language?

The "same" is what

**Comment by PadowYT2** [comment]
> Can you show some images before and after your additions?

image
image

**Comment by Sylensky** [comment]
From 11f2724 but for russian language.

**Review by Sylensky — APPROVED** [review]

**Pull request merged**
